"""Base Strategy class for WEEX trading."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional
from enum import Enum


class SignalAction(str, Enum):
    """Trading signal actions."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE = "close"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    action: SignalAction
    symbol: str
    size: float
    price: Optional[float] = None
    stop_price: Optional[float] = None  # Stop loss
    target_price: Optional[float] = None  # Take profit
    reason: str = ""
    confidence: float = 0.0
    strategy: str = ""  # Strategy that generated this signal
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    # AI-related fields for logging
    model_used: Optional[str] = None
    ai_explanation: Optional[str] = None


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""

    name: str = "base"
    version: str = "1.0.0"
    description: str = "Base strategy"

    def __init__(self, strategy_id: str, config: Dict[str, Any]):
        """Initialize strategy.

        Args:
            strategy_id: Unique identifier for this strategy instance
            config: Strategy configuration
        """
        self.strategy_id = strategy_id
        self.config = config
        self.params = config.get("params", {})
        self._running = False
        self._signals: List[Signal] = []

    @abstractmethod
    async def on_tick(self, tick: Dict[str, Any]) -> Optional[Signal]:
        """Process a market tick and optionally generate a signal.

        Args:
            tick: Market tick data

        Returns:
            Trading signal or None
        """
        pass

    async def on_start(self):
        """Called when strategy starts."""
        self._running = True

    async def on_stop(self):
        """Called when strategy stops."""
        self._running = False

    def create_signal(
        self,
        action: SignalAction,
        symbol: str,
        size: float,
        price: Optional[float] = None,
        reason: str = "",
        confidence: float = 0.0,
        model_used: Optional[str] = None,
        ai_explanation: Optional[str] = None,
        **kwargs,
    ) -> Signal:
        """Create a trading signal.

        Args:
            action: Signal action
            symbol: Trading pair
            size: Order size
            price: Limit price (optional)
            reason: Reason for signal
            confidence: Confidence score (0-1)
            model_used: AI model that generated this signal
            ai_explanation: AI explanation for the signal
            **kwargs: Additional metadata

        Returns:
            Signal object
        """
        signal = Signal(
            action=action,
            symbol=symbol,
            size=size,
            price=price,
            reason=reason,
            confidence=confidence,
            model_used=model_used,
            ai_explanation=ai_explanation,
            metadata=kwargs,
        )
        self._signals.append(signal)
        return signal

    @classmethod
    def get_parameters_schema(cls) -> Dict[str, Any]:
        """Get schema for configurable parameters.

        Override in subclasses to define parameters.

        Returns:
            Parameter schema dictionary
        """
        return {}

    def get_metrics(self) -> Dict[str, Any]:
        """Get strategy metrics.

        Returns:
            Dictionary of metrics
        """
        return {
            "strategy_id": self.strategy_id,
            "name": self.name,
            "version": self.version,
            "running": self._running,
            "total_signals": len(self._signals),
        }

    @property
    def is_running(self) -> bool:
        """Check if strategy is running."""
        return self._running
